import { Box, Flex } from '@chakra-ui/react';
import Head from 'next/head';
import React from 'react';

import { Footer } from './Footer';
import { NavBar } from './NavBar';

export function Layout({ children }) {
  return (
    <Flex direction="column" minHeight="100vh">
      <Head>
        <title>Smart Invoice</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <Box flexGrow={1}>{children}</Box>
      <Footer />
    </Flex>
  );
}
